version: '3.1'

services:

  db:
    image: mahendrshinde/mysql-sample:sakila
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass@123456
      MYSQL_USER: mahendra
      MYSQL_PASSWORD: password@1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080